### PR TITLE
Saving the entire URL on the Repository Widgets

### LINKED ISSUE #396: Issue widget keep forgetting query
### Dev Home version

0.1401.505.0

### Windows build number

10.0.19045.0

### Other software

_No response_

### Steps to reproduce the bug

GH_IS

- Add a new issue widget with a query like `https://github.com/microsoft/PowerToys/issues?q=is%3Aopen+is%3Aissue+label%3AIssue-Bug`
- Save
- Note that the widget shows the correct issues filtered by the query
- Customize
- Cancel
- The widget query is removed

Sometimes the query is removed after restarting DevHome.

### Expected result

_No response_

### Actual result

The query shouldn't disappear.

### Included System Information

_No response_

### PR DESCRIPTION
**Pull request by guimafelipe**
## Summary of the pull request
When the widget was being saved, we changed the data to include only the main URL, without the query. This created a bug when if the user customized the widget but cancelled the process, the widget would lose track of its query because it was not being saved on the `ConfigurationData`. With this PR, we never change the actual URL that the user used as input, keeping it consistent.

This PR also fixes the issue where we could save widgets with invalid URLs. This would happen if the user submit a URL, change it for some reason, and then save the widget. As the save action also gets data (important to get the last title input for example), we need to correct it to the URL we are sure is correct.

## PR checklist
- [ ] Closes #396
- [ ] Tests added/passed
- [ ] Documentation updated

### CODE REVIEW

**Review by krschau — APPROVED** [review]

File: src/GitHubExtension/Widgets/GitHubRepositoryWidget.cs [hunk 1]
```diff
@@ -46,6 +46,19 @@ public string GetUnescapedIssueQuery()
         return Uri.UnescapeDataString(GetIssueQuery()).Replace('+', ' ');
     }
 
+    // If the user changed the URL after clicking submit and clicked
+    // saved just after, we change it back to what was before to not corrupt our saved data.
+    private void CorrectUrl()
```
Comment (dhoehna) [inline src/GitHubExtension/Widgets/GitHubRepositoryWidget.cs:51]: The comments sound like a race-condition.  What is happening between "Submit" and "Save"?

**Review by dhoehna — APPROVED** [review]

File: src/GitHubExtension/Widgets/GitHubRepositoryWidget.cs (hunk 1 above)
Comment (krschau) [reply src/GitHubExtension/Widgets/GitHubRepositoryWidget.cs:51]: They are separate buttons in the widget, so unlikely that the user could click them both fast enough to cause an issue.
