### PR TITLE
Corrected spelling (and casing) of error messages

### LINKED ISSUE #258: Typo in exception message
### Dev Home version

_No response_

### Windows build number

_No response_

### Other software

_No response_

### Steps to reproduce the bug

1. clone a repo that is not accessible (or otherwise causes an Exception)
2. the error message shown contains a small typo: "LigGet2" instead of "LibGet2". (see screenshot). 
image

### Expected result

Correct spelling and / or casing.

### Actual result

Incorrect spelling (small typo) shown.

### Included System Information

_No response_

### PR DESCRIPTION
**Pull request by ElmarJ**
## Summary of the pull request
Minor changes to exception messages, solving a typo and incorrect casing

## References and relevant issues
#258

## Detailed description of the pull request 

Maybe the Libgit2-exception should be rephrased entirely to be more helpful for end users, but that's beyond the aim of this small PR.

## PR checklist
- [x] Closes #258

### CODE REVIEW

File: src/GitHubExtension/Providers/RepositoryProvider.cs [hunk 1]
```diff
@@ -239,12 +239,12 @@ public IAsyncOperation<ProviderOperationResult> CloneRepositoryAsync(IRepository
...
             {
                 Providers.Log.Logger()?.ReportError("DevHomeRepository", $"Either no logged in account has access to this repo, or the repo can't be found", libGitTwoException);
-                return new ProviderOperationResult(ProviderOperationStatus.Failure, libGitTwoException, "LigGit2 threw an exception", "LibGit2 Threw an exception");
+                return new ProviderOperationResult(ProviderOperationStatus.Failure, libGitTwoException, "LibGit2 threw an exception", "LibGit2 threw an exception");
             }
             catch (Exception e)
             {
                 Providers.Log.Logger()?.ReportError("DevHomeRepository", "Could not clone the repository", e);
-                return new ProviderOperationResult(ProviderOperationStatus.Failure, e, "Something happened when cloning the repo", "something happened when cloning the repo");
+                return new ProviderOperationResult(ProviderOperationStatus.Failure, e, "Something happened when cloning the repo", "Something happened when cloning the repo");
```
Comment (dkbennett) [inline src/GitHubExtension/Providers/RepositoryProvider.cs:247]: I know this is a bit nitpicky, but the entire PR/issue is basically a nitpick, so I think it's warranted. If we're going to fix this sort of issue, we should make whatever is touched as correct as possible, so we don't have to fix it again later.

Two issues I see here:
1) Use of abbreviations.  The abbreviation "repo" is used instead of "repository. Abbreviations and slang are to be avoided. Yes, I know this is all over the code, but if going to change something make it right as we go. 
2) All the error messages touched in this PR are not complete sentences. Namely just add a period at the end.
 
https://learn.microsoft.com/en-us/windows/win32/debug/error-message-guidelines

**Review by dkbennett — CHANGES_REQUESTED** [review]

File: src/GitHubExtension/Providers/RepositoryProvider.cs (hunk 1 above)
Comment (ElmarJ) [reply src/GitHubExtension/Providers/RepositoryProvider.cs:247]: Thanks, I'll make these corrections. 

BTW: I agree that this PR is a nitpick, But I actually did spent several minutes trying to figure out / web searching what "LitGit2" meant in the error dialogue I received before I realized it was a typo (I know, not my brightest moment) - hence the PR.

Comment (ElmarJ) [reply src/GitHubExtension/Providers/RepositoryProvider.cs]: Updated the PR. I checked all messages for spelling errors, punctuation, abbreviations and made a few small changes to improve clarity.

**Review by dkbennett — APPROVED** [review]

**Review by krschau — APPROVED** [review]

**Review by EricJohnson327 — APPROVED** [review]
